[["EL CONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA", 1354],
 ["EL INTERVENTOR MUNICIPAL SANCIONA CON FUERZA DE ORDENANZA", 170],
 ["EL INTENDENTE MUNICIPAL SANCIONA CON FUERZA DE ORDENANZA", 3],
 ["EL INTENDENTE MUNICIPAL SANCIONA Y PROMULGA CON FUERZA DE ORDENANZA", 1],
 ["El CONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA", 1]]