require 'pp'
#Esto es nuevo
Sanciona = 
[["EL CONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA", 1376],
 ["EL INTERVENTOR MUNICIPAL SANCIONA CON FUERZA DE ORDENANZA", 80],
 ["EL INTERVENTOR MUNICIPAL SANCIONA Y PROMULGA CON FUERZA DE ORDENANZA", 38],
 ["SANCIONA Y PROMULGA CON FUERZA DE ORDENANZA", 31],
 ["EL COMISIONADO INTERVENTOR DE LA MUNICIPALIDAD DE YERBA BUENA SANCIONA Y PROMULGA CON FUERZA DE ORDENANZA", 20],
 ["EL INTERVENTOR MUNICIOAL SANCIONA Y PROMULGA CON FUERZA DE ORDENANZA", 9],
 ["EL CONSEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA", 7],
 ["EL CONCEJO DELIBERANTESANCIONA CON FUERZA DE ORDENANZA", 7],
 ["EL INTENDENTE MUNICIPAL SANCIONA Y PROMULGA CON FUERZA DE ORDENANZA", 4],
 ["EL CONCEJO DELIBERANTESANCIONA CON FUERZA DEORDENANZA", 3],
 ["SANCIONA CON FUERZA DE ORDENANZA", 3],
 ["POR EL CONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA", 2],
 ["EL INTERVENTOR MUNICIPALSANCIONA CON FUERZA DE ORDENANZA", 2],
 ["INTERVENTOR MUNICIPAL SANCIONA Y PROMULGA CON FUERZA DE ORDENANZA", 2],
 ["EL INTERVENTOR MUNICIPAL SANCIONA Y PROMUNGA CON FUERZA DEORDENANZA", 2],
 ["EL INTERVENTOR MUNICIPAL SANCIONA Y CON FUERZA DE ORDENANZA", 1],
 ["EL INTERVENTOR MUNICIPA SANCIONA Y PROMULGA CON FUERZA DE ORDENANZA", 1],
 ["QUE LA PRESENTE ORDENANZA DEBERÁ SER, MODIFICATORIA Y ACLARATORIA DE LA PRIMERA, CONSTITUYÉNDOSE AMBAS EN LA NORMA QUE REGULE EL ACCIONAR DE LA FARMACIA SOCIAL “PEDRO MADERUEL CONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA", 1],
 ["EL SECRETARIO DE GOBIERNO, OBRAS Y SERVICIOS PUBLICOS SANCIONA Y PROMULGA CON FUERZA DE ORDENANZA", 1],
 ["EL HONORABLE CONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA", 1],
 ["EL INTERVENTOR MUNICIPAL SANCIONA Y PROMULGACON FUERZA DE ORDENANZA", 1],
 ["EL INTERVENTOR MUNICIPAL SANCIONAY PROMULGA CON FUERZA DE ORDENANZA", 1],
 ["ELCONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA", 1],
 ["SANCIONAY PROMULGA CON FUERZA DE ORDENANZA", 1],
 ["EL CONCEJO DELIBERANTE SANCIONA CON FUERZA ORDENANZA", 1],
 ["EL CONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA N° 1481ANEXOI", 1],
 ["CONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA", 1]]

Limpieza = 
[
 [/CONSEJO.*SANCIONA.*ORDENANZA/,'EL CONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA'],
 [/INTERVENTOR.*SANCIONA.*ORDENANZA/,'EL INTERVENTOR SANCIONA CON FUREZA DE ORDENANZA'],
 [/CONCEJO.*SANCIONA.*ORDENANZA/,'EL CONCEJO DELIBERANTE SANCIONA CON FUERZA DE ORDENANZA'],
]

pp Sanciona.select{|t, n| !Limpieza.any?{|a, b| t[a]}}